[build]
  publish = "build/web"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  FLUTTER_WEB = "true"
  FLUTTER_VERSION = "3.32.8"
  FLUTTER_ROOT = "/opt/buildhome/.flutter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"